import {
  CRA_FOCUS_SECTION_LABELS,
  CRA_FOCUS_SECTION_ORDER,
  MONITORING_SECTION_LABELS,
  MONITORING_SECTION_ORDER,
  RISK_SECTION_LABELS,
  RISK_SECTION_ORDER,
  SITE_TRAINING_SECTION_LABELS,
  SITE_TRAINING_SECTION_ORDER,
  SIV_SECTION_LABELS,
  SIV_SECTION_ORDER,
  type DeliverableArtifactType,
} from '../../types/deliverables';

// =============================================================================
// deliverableExportConfig — per-artifact export vocabulary for the portrait
// PDF builder (buildDeliverablePdf). One exhaustive
// Record<DeliverableArtifactType, …> so adding a sixth artifact type cannot
// compile without describing how it exports — the same type-forced discipline
// the panel's DELIVERABLE_CONFIGS / DELIVERABLE_COPY use.
//
// Lives in the lib layer (imports only types/deliverables) so the export API
// stays free of any src/components import.
//
// Draft-only doctrine, enforced structurally + by test:
//   - every headerLabel carries "PIQC drafted · … · DRAFT";
//   - every disclaimer carries the compliance tokens (source-backed · draft ·
//     outside PIQC) and never uses approval vocabulary.
//
// siv_package has an entry for completeness (filename slug + a future portrait
// path), but the SIV deck ships through its own landscape builder
// (exporters/buildSivDeck) with its own header/disclaimer; only the filename
// helper is shared.
// =============================================================================

export interface DeliverableExportConfig {
  /** Render order for the PDF's per-section tables. */
  sectionOrder: readonly string[];
  sectionLabels: Record<string, string>;
  /** Middle segment of the filename: <code>_<slug>_draft_<date>.pdf. */
  filenameSlug: string;
  /** Corner/header band label. */
  headerLabel: string;
  /** Footer disclaimer — draft-only, source-backed, control-stays-outside-PIQC. */
  disclaimer: string;
}

export const DELIVERABLE_EXPORT_CONFIGS: Record<
  DeliverableArtifactType,
  DeliverableExportConfig
> = {
  monitoring_prep_checklist: {
    sectionOrder: MONITORING_SECTION_ORDER,
    sectionLabels: MONITORING_SECTION_LABELS,
    filenameSlug: 'monitoring_prep_checklist',
    headerLabel: 'PIQC drafted · Monitoring preparation checklist · DRAFT',
    disclaimer:
      'This checklist was generated by PIQC as a source-backed draft ' +
      'preparation aid. Monitoring decisions, final content, and controlled ' +
      "release remain with your organization's designated process outside PIQC.",
  },
  risk_overview: {
    sectionOrder: RISK_SECTION_ORDER,
    sectionLabels: RISK_SECTION_LABELS,
    filenameSlug: 'risk_overview',
    headerLabel: 'PIQC drafted · Protocol risk overview · DRAFT',
    disclaimer:
      'This risk overview was generated by PIQC as a source-backed draft. ' +
      'Risk interpretation, prioritization, and any resulting action remain ' +
      "with your organization's designated process outside PIQC.",
  },
  cra_monitoring_focus: {
    sectionOrder: CRA_FOCUS_SECTION_ORDER,
    sectionLabels: CRA_FOCUS_SECTION_LABELS,
    filenameSlug: 'cra_monitoring_focus',
    headerLabel: 'PIQC drafted · CRA monitoring focus · DRAFT',
    disclaimer:
      'This monitoring focus was generated by PIQC as a source-backed draft ' +
      'preparation aid. Monitoring decisions, final content, and controlled ' +
      "release remain with your organization's designated process outside PIQC.",
  },
  siv_package: {
    sectionOrder: SIV_SECTION_ORDER,
    sectionLabels: SIV_SECTION_LABELS,
    filenameSlug: 'siv_package',
    headerLabel: 'PIQC drafted · SIV knowledge transfer package · DRAFT',
    disclaimer:
      'This SIV package was generated by PIQC as a source-backed draft. ' +
      'Training content, final materials, and controlled release remain with ' +
      "your organization's designated process outside PIQC.",
  },
  site_training_priorities: {
    sectionOrder: SITE_TRAINING_SECTION_ORDER,
    sectionLabels: SITE_TRAINING_SECTION_LABELS,
    filenameSlug: 'site_training_priorities',
    headerLabel: 'PIQC drafted · Site training priorities · DRAFT',
    disclaimer:
      'These site training priorities were generated by PIQC as a ' +
      'source-backed draft. Training scope, final content, and controlled ' +
      "release remain with your organization's designated process outside PIQC.",
  },
};

/** Narrowing guard for a server-supplied artifact_type string — the whitelist
 *  is the config's own keys (whitelist-from-the-map, never a hand-listed set
 *  that silently goes stale). */
export function isExportableArtifactType(value: unknown): value is DeliverableArtifactType {
  return typeof value === 'string' &&
    Object.prototype.hasOwnProperty.call(DELIVERABLE_EXPORT_CONFIGS, value);
}
