// =============================================================================
// Visit Execution Workspace — Export pipeline (Sprint 5).
//
// Three layers, each separately testable (pattern from src/lib/sotr/exportApi.ts):
//
//   1. fetchVisitWorksheetPacket — supabase.rpc('visit_execution_export_worksheet').
//                                  Returns Result<T> per CLAUDE.md API convention
//                                  (no throw outside programmer-error guards).
//                                  Mock-mode short-circuit synthesizes a packet
//                                  from mockVisitWorkspace.ts.
//
//   2. buildVisitWorksheetPdf — pure function: packet → jsPDF document.
//                               No DOM, no Blob, no download — testable without
//                               jsdom shenanigans.
//
//   3. downloadVisitWorksheet — orchestrates fetch + build + Blob + click.
//                               Returns Result<{filename, itemCount}>.
//
// "worksheet" is the deliverable noun (per product_vew_workspace_vs_worksheet_model.md):
//   - Button label: "Export worksheet"
//   - Filename: <protocol_code>_<visit_name>_worksheet_draft_<YYYY-MM-DD>.pdf
//   - PDF header: "PIQC drafted · Visit worksheet · DRAFT"
//   - Footer disclaimer below
//
// Sponsor-name-free: the RPC excludes protocols.sponsor; this builder never
// renders sponsor branding regardless of whether the packet somehow carries it.
// =============================================================================

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * jspdf-autotable patches the jsPDF instance with `lastAutoTable` after each
 * autoTable() call so callers can read where the table ended. The library
 * ships no type augmentation for this, so we declare a narrow shape here
 * (used only to read .finalY between autoTables — see body composition
 * below). Avoids `as any` in production code.
 */
interface JsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: { finalY?: number };
}
import { supabase } from '../supabase';
import type { Result } from '../site/siteApi';
import type {
  ExecutionPhase,
  ItemClassification,
  ExecutionReviewStatus,
  RoleFilter,
  VisitWorksheetExportPacket,
  VisitWorksheetExportRow,
} from '../../types/visit-execution';
import {
  PHASE_LABELS_DOSING,
  PHASE_LABELS_NON_DOSING,
  ROLE_LABELS,
} from '../../types/visit-execution';
import { itemMatchesRoleFilter } from './parseRoleHint';
import {
  CONFIDENCE_SHORT_LABELS,
  deriveVisitConfidence,
} from './deriveVisitConfidence';
import { isMockEnabled } from './visitExecutionApi';
import { getMockVisitExecutionWorkspaces } from './mockVisitWorkspace';
import { DEMO_PROTOCOL_IDS } from '../demo/ids';

// ---------------------------------------------------------------------------
// Disclaimer + naming constants
// ---------------------------------------------------------------------------

export const WORKSHEET_DISCLAIMER =
  'This worksheet was generated by PIQC as a draft aid. Final accuracy, ' +
  'compliance verification, source-document authoring, and approval occur ' +
  "outside PIQC in the site's designated process or system.";

export const WORKSHEET_HEADER_LABEL = 'PIQC drafted · Visit worksheet · DRAFT';

/**
 * Canonical placeholder purpose prose — emitted by the v2/v3 RPC when no
 * structured `purpose` has been extracted yet. The PDF builder renders this
 * differently (italic gray, framed as "parser-pending") so the deliverable
 * doesn't look like an unfinished worksheet to a coordinator who exports
 * before re-running the ingest.
 *
 * Kept in sync with the COALESCE fallback in
 * supabase/migrations/20260617000000_visit_execution_export_rpc.sql (and
 * the older visit_execution_get_workspace RPCs).
 */
export const WORKSHEET_PLACEHOLDER_PURPOSE =
  'Per-protocol visit. Detailed execution requirements pending structured ingest extraction.';

// ---------------------------------------------------------------------------
// Filename helper
// ---------------------------------------------------------------------------

/**
 * Slugify a name for filesystem-safe filenames: lowercase, alphanumerics +
 * dashes + underscores only, collapse runs of separators.
 */
export function slugifyForFilename(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'untitled';
}

/**
 * Extract the YYYY-MM-DD date portion from an ISO 8601 timestamp.
 *
 * Uses UTC (matches the PDF footer's `Generated YYYY-MM-DD HH:MM UTC`
 * format). The packet's `generated_at` is the server-clock authoritative
 * lock-in time — pulling the date from THAT source means the filename
 * always matches the footer regardless of browser timezone.
 *
 * Falls back to today's UTC date if the input is unparseable (defensive —
 * the RPC should never return a malformed timestamp, but the API boundary
 * shouldn't crash the export over it).
 */
export function isoDateForFilename(iso: string): string {
  try {
    const d = new Date(iso);
    if (!Number.isNaN(d.getTime())) {
      const y = d.getUTCFullYear();
      const m = String(d.getUTCMonth() + 1).padStart(2, '0');
      const day = String(d.getUTCDate()).padStart(2, '0');
      return `${y}-${m}-${day}`;
    }
  } catch {
    // Fall through to today's date.
  }
  const fallback = new Date();
  const m = String(fallback.getUTCMonth() + 1).padStart(2, '0');
  const day = String(fallback.getUTCDate()).padStart(2, '0');
  return `${fallback.getUTCFullYear()}-${m}-${day}`;
}

/**
 * Build the filename for an exported worksheet.
 * Format (canonical / all roles):
 *   `<protocol_code>_<visit_name>_worksheet_draft_<YYYY-MM-DD>.pdf`
 * Format (Sprint 6 — role-scoped):
 *   `<protocol_code>_<visit_name>_<role>_worksheet_draft_<YYYY-MM-DD>.pdf`
 *
 * Protocol code falls back to a short id prefix when null (e.g. `protocol_8f3a`).
 * Date comes from `packet.generated_at` (the server-stamped lock-in time)
 * NOT the browser clock — filename and footer timestamp must agree.
 *
 * `roleFilter` defaults to `'all'` so existing callers without role-awareness
 * keep their pre-Sprint-6 filename shape.
 */
export function buildWorksheetFilename(
  packet: Pick<VisitWorksheetExportPacket, 'protocol_code' | 'protocol_id' | 'snapshot' | 'generated_at'>,
  roleFilter: RoleFilter = 'all',
): string {
  const code = packet.protocol_code
    ? slugifyForFilename(packet.protocol_code)
    : `protocol_${packet.protocol_id.slice(0, 4)}`;
  const visit = slugifyForFilename(packet.snapshot.visit_name);
  const roleSegment = roleFilter === 'all' ? '' : `_${roleFilter}`;
  return `${code}_${visit}${roleSegment}_worksheet_draft_${isoDateForFilename(packet.generated_at)}.pdf`;
}

// ---------------------------------------------------------------------------
// Layer 1 — fetch
// ---------------------------------------------------------------------------

/**
 * Mock-mode synthetic packet builder. Pulls the requested visit from the
 * mock workspace fixture and shapes it into the export packet — same
 * structure the real RPC returns, so demos download a real PDF.
 *
 * Returns null when the visit_template_id isn't in the fixture (e.g. wrong
 * protocol id passed in mock mode).
 */
function buildMockPacket(visitTemplateId: string): VisitWorksheetExportPacket | null {
  // Mock fixture is keyed by protocol id. We only have a visit_template_id
  // here, so scan all known demo protocols for the requested visit. The
  // fixtures are tiny; scanning is fine. BRIGHTEN-2 is the canonical demo
  // (Sprint 1 ships visits under it); the other two are listed so a future
  // multi-protocol fixture doesn't require touching this file.
  const protocolIds: string[] = [
    DEMO_PROTOCOL_IDS['BRIGHTEN-2'],
    DEMO_PROTOCOL_IDS['CARDIAC-7'],
    DEMO_PROTOCOL_IDS['IMMUNE-14'],
  ];
  let workspace = null;
  let foundProtocolId: string | null = null;
  for (const pid of protocolIds) {
    const match = getMockVisitExecutionWorkspaces(pid).find(
      (w) => w.visit_template_id === visitTemplateId,
    );
    if (match) {
      workspace = match;
      foundProtocolId = pid;
      break;
    }
  }
  if (!workspace || !foundProtocolId) return null;

  // Map the demo protocol UUID back to its human code for the filename.
  const protocolCode =
    (Object.entries(DEMO_PROTOCOL_IDS).find(([, id]) => id === foundProtocolId)?.[0]) ?? null;

  return {
    protocol_id: workspace.protocol_id,
    protocol_code: protocolCode,
    protocol_title: `${protocolCode ?? 'Demo protocol'} (mock fixture)`,
    visit_template_id: workspace.visit_template_id,
    generated_at: new Date().toISOString(),
    snapshot: {
      visit_name: workspace.snapshot.visit_name,
      study_day: workspace.snapshot.study_day,
      window_minus_days: workspace.snapshot.window_minus_days,
      window_plus_days: workspace.snapshot.window_plus_days,
      purpose: workspace.snapshot.purpose,
      is_dosing_visit: workspace.snapshot.is_dosing_visit,
      has_primary_endpoint: workspace.snapshot.has_primary_endpoint,
      has_safety_critical: workspace.snapshot.has_safety_critical,
      item_count: workspace.snapshot.item_count,
      reviewed_count: workspace.snapshot.reviewed_count,
      needs_review_count: workspace.snapshot.needs_review_count,
      amendment_version: workspace.snapshot.amendment_version,
      confidence_state: workspace.snapshot.confidence_state,
      completeness_signal_count: workspace.snapshot.completeness_signal_count,
    },
    items: workspace.items.map((item, idx) => ({
      id: item.id,
      phase: item.phase,
      phase_order: idx + 1,
      ordinal: idx + 1,
      label: item.label,
      description: item.description,
      classification: item.classification,
      role_hint: item.role_hint,
      review_status: item.review_status,
      review_note: item.review_note,
      // Mock fixture has no `origin` field; treat as parser-derived.
      origin: 'soa_cell' as const,
      conditions: item.conditions,
      timing: item.timing,
      source_fields: item.source_fields,
      confidence_state: item.confidence_state,
      traceability: {
        soa_column: item.traceability.soa_column,
        protocol_section: item.traceability.protocol_section,
        protocol_page: item.traceability.protocol_page,
        amendment_version: item.traceability.amendment_version,
      },
    })),
  };
}

/**
 * Fetch the worksheet packet for one visit.
 *
 * Mock-mode short-circuits with a synthetic packet (so demos download a
 * real PDF). Real-mode wraps the RPC + defensive narrowing.
 */
export async function fetchVisitWorksheetPacket(
  visitTemplateId: string,
): Promise<Result<VisitWorksheetExportPacket>> {
  if (isMockEnabled()) {
    const packet = buildMockPacket(visitTemplateId);
    if (!packet) {
      return { ok: false, error: 'No mock fixture for this visit' };
    }
    return { ok: true, data: packet };
  }

  const { data, error } = await supabase.rpc('visit_execution_export_worksheet', {
    p_visit_template_id: visitTemplateId,
  });

  if (error) {
    return { ok: false, error: error.message };
  }

  // Defensive shape check at the boundary. Per Sprint 4c lesson: drop rather
  // than crash.
  const payload = data as Partial<VisitWorksheetExportPacket> | null;
  if (
    !payload ||
    typeof payload.protocol_id !== 'string' ||
    typeof payload.visit_template_id !== 'string' ||
    typeof payload.generated_at !== 'string' ||
    !payload.snapshot ||
    !Array.isArray(payload.items)
  ) {
    return { ok: false, error: 'malformed worksheet packet' };
  }

  return {
    ok: true,
    data: {
      protocol_id: payload.protocol_id,
      protocol_code: typeof payload.protocol_code === 'string' ? payload.protocol_code : null,
      protocol_title:
        typeof payload.protocol_title === 'string' ? payload.protocol_title : 'Untitled protocol',
      visit_template_id: payload.visit_template_id,
      generated_at: payload.generated_at,
      snapshot: payload.snapshot,
      items: payload.items,
    },
  };
}

// ---------------------------------------------------------------------------
// Layer 2 — pure PDF build
// ---------------------------------------------------------------------------

/**
 * Phase render order. Mirrors EXECUTION_PHASE_ORDER from the types file.
 */
const PHASE_ORDER: ExecutionPhase[] = [
  'pre_visit',
  'check_in',
  'assessment',
  'dosing',
  'post_dose',
  'safety_ae_conmed',
  'close_out',
];

/**
 * Compact labels for the table cells. Mirrors the workspace UI labels but
 * tighter (no surrounding chip chrome — just the word).
 */
const CLASSIFICATION_LABEL: Record<ItemClassification, string> = {
  required:           'Required',
  conditional:        'Conditional',
  if_applicable:      'If Applicable',
  primary_endpoint:   'Primary Endpoint',
  secondary_endpoint: 'Secondary Endpoint',
  safety_critical:    '⚠ Safety Critical',
};

const REVIEW_LABEL: Record<ExecutionReviewStatus, string> = {
  not_reviewed:    'Not reviewed',
  // "!" prefix gives needs_review a visual flag for at-a-glance scanning
  // on a printed page where color and weight aren't reliable cues.
  needs_review:    '! Needs review',
  reviewed:        'Reviewed ✓',
  edited:          'Edited',
  site_note_added: 'Site note',
};

/**
 * Format the timing constraint for a print row. Returns "—" when no timing.
 */
function formatTiming(row: VisitWorksheetExportRow): string {
  if (!row.timing) return '—';
  const t = row.timing;
  // Hard-constraint label gets a "!" flag for at-a-glance differentiation.
  const flag = t.is_hard_constraint ? '! ' : '';
  return `${flag}${t.label}`;
}

/**
 * Build a multi-line "Requirement" cell: label + (optional) description +
 * inline conditional rules + inline source fields. Returns a single string
 * with \n separators — autotable handles wrapping.
 */
function formatRequirementCell(row: VisitWorksheetExportRow): string {
  const lines: string[] = [row.label];

  if (row.description) {
    lines.push(row.description);
  }

  for (const c of row.conditions) {
    lines.push(`If: ${c.condition_text}`);
    lines.push(`Then: ${c.consequence_text}`);
  }

  if (row.source_fields.length > 0) {
    const fields = row.source_fields
      .map((f) => `${f.field_label}${f.units ? ` (${f.units})` : ''}${f.is_required ? '*' : ''}`)
      .join(', ');
    lines.push(`Source fields: ${fields}`);
  }

  if (row.review_note) {
    lines.push(`Site note: ${row.review_note}`);
  }

  // Add a marker for human-added rows so coordinators can see at a glance
  // which items came from PIQC's draft vs were added during review.
  if (row.origin === 'human_added') {
    lines.push('(Coordinator-added during review)');
  }

  return lines.join('\n');
}

/**
 * Format the study-day + window into one print-friendly line.
 */
function formatWindow(snapshot: VisitWorksheetExportPacket['snapshot']): string {
  const day = snapshot.study_day >= 0 ? `+${snapshot.study_day}` : `${snapshot.study_day}`;
  if (snapshot.window_minus_days === 0 && snapshot.window_plus_days === 0) {
    return `Day ${day} · fixed (no permissible window)`;
  }
  if (snapshot.window_minus_days === snapshot.window_plus_days) {
    return `Day ${day} · ± ${snapshot.window_plus_days} day${snapshot.window_plus_days === 1 ? '' : 's'}`;
  }
  return `Day ${day} · −${snapshot.window_minus_days} / +${snapshot.window_plus_days} days`;
}

/**
 * Format the server-stamped timestamp into a "Generated YYYY-MM-DD HH:MM UTC"
 * line for the PDF footer.
 */
function formatGeneratedAt(iso: string): string {
  try {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso;
    const y = d.getUTCFullYear();
    const mo = String(d.getUTCMonth() + 1).padStart(2, '0');
    const day = String(d.getUTCDate()).padStart(2, '0');
    const hh = String(d.getUTCHours()).padStart(2, '0');
    const mm = String(d.getUTCMinutes()).padStart(2, '0');
    return `Generated ${y}-${mo}-${day} ${hh}:${mm} UTC`;
  } catch {
    return iso;
  }
}

/**
 * Pure function: packet → jsPDF document.
 *
 * Layout (US Letter portrait):
 *   - First page only: title block (visit name + window + purpose + stats)
 *   - All pages: header band ("PIQC drafted · Visit worksheet · DRAFT")
 *                + footer band (disclaimer + Generated <ts> + page X/Y)
 *   - Body: one autotable per non-empty phase
 *   - Last: traceability appendix (per-item protocol section + page)
 *
 * Sprint 6 — when `roleFilter` is non-`'all'`:
 *   - Items filtered (in-place packet not mutated; filtered local view used)
 *   - Title block gets a "Filtered view: <Role>" subtitle line
 *   - Stats line scopes to filtered counts
 *   - Open-items warning banner scopes to filtered counts
 *   - Traceability appendix scopes to filtered items
 *
 * Returns the jsPDF instance so callers can .save() / .output() / inspect
 * in tests.
 */
export function buildVisitWorksheetPdf(
  packet: VisitWorksheetExportPacket,
  roleFilter: RoleFilter = 'all',
): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'letter', orientation: 'portrait' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48; // 0.67" — gives autotable room to breathe.

  const phaseLabels = packet.snapshot.is_dosing_visit
    ? PHASE_LABELS_DOSING
    : PHASE_LABELS_NON_DOSING;

  // Sprint 6: apply the role lens. Filter the items list and recompute
  // the snapshot counts so the title block + banner + stats line
  // reflect what's actually on the page. The packet is NOT mutated; the
  // original totals stay accessible for tests / future re-renders.
  //
  // VisitWorksheetExportRow exposes role_hint directly (see types file),
  // so the filter is a simple substring match via the canonical
  // itemMatchesRoleFilter helper. Unscoped rows (null role_hint / "Site
  // staff" / etc.) appear under every role — clinical-default safety.
  const isFiltered = roleFilter !== 'all';
  const filteredItems = isFiltered
    ? packet.items.filter((i) => itemMatchesRoleFilter(i.role_hint, roleFilter))
    : packet.items;
  const filteredReviewedCount = isFiltered
    ? filteredItems.filter((i) => i.review_status === 'reviewed').length
    : packet.snapshot.reviewed_count;
  const filteredNeedsReviewCount = isFiltered
    ? filteredItems.filter(
        (i) => i.review_status === 'not_reviewed' || i.review_status === 'needs_review',
      ).length
    : packet.snapshot.needs_review_count;

  // ---- Title block (first page) -------------------------------------------
  let cursorY = margin + 28;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(WORKSHEET_HEADER_LABEL, margin, margin);

  doc.setTextColor(20);
  doc.setFontSize(18);
  doc.text(packet.snapshot.visit_name, margin, cursorY);
  cursorY += 22;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(60);
  doc.text(formatWindow(packet.snapshot), margin, cursorY);
  cursorY += 16;

  doc.setFontSize(9);
  doc.setTextColor(110);
  // Protocol title + code on one line. NO sponsor — sponsor-name-free.
  const codeLabel = packet.protocol_code
    ? `${packet.protocol_title} · ${packet.protocol_code}`
    : packet.protocol_title;
  doc.text(codeLabel, margin, cursorY);
  cursorY += 16;

  // Sprint 6: filtered-view subtitle. Only renders when a role lens is
  // active. Sits between the protocol-code line and the purpose section
  // so a coordinator scanning the page knows immediately "this is the
  // <Role> view of the worksheet, not the full visit."
  // Sprint 7: derived visit-level confidence. Computed against the
  // already-filtered item set so the rollup matches what the PDF actually
  // contains. Surfaced as a label line below the protocol-title/code line
  // and again in the title block when the rollup is non-'high' (cognitive-
  // load discipline). Per-item confidence renders in the autotable column
  // below.
  //
  // Coordinator-facing intent (re-confirmed 2026-05-30): the coordinator
  // handing off the worksheet should KNOW PIQC's confidence in the
  // underlying extraction, not have to guess. Hiding the indicator while
  // per-item confidence is improving would treat a symptom.
  const visitConfidence = deriveVisitConfidence(packet.snapshot, filteredItems);

  // `isFiltered` already implies `roleFilter !== 'all'`; second check
  // would be redundant. The inner narrow uses a type-only guard cast
  // because TypeScript can't trace the equivalence across the variable.
  if (isFiltered) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    // Blue-800 (approx 30, 64, 175) — matches the existing TimingBanner
    // informational accent. Avoids introducing a NEW color (indigo would
    // have) for a label that serves the same "informational, not
    // warning" semantic role.
    doc.setTextColor(30, 64, 175);
    doc.text(
      `Filtered view: ${ROLE_LABELS[roleFilter as Exclude<RoleFilter, 'all'>]}`,
      margin,
      cursorY,
    );
    doc.setFont('helvetica', 'normal');
    cursorY += 14;
  }

  // Sprint 7: visit-level confidence label. Always shown — the deliverable
  // is the moment-of-lock-in and the coordinator handing it off should
  // KNOW PIQC's confidence in the underlying extraction, not have to
  // guess.
  //
  // Color discipline (post-design-critique): only alarm states earn
  // color in the PDF. high + medium use the default protocol-code gray;
  // low + needs_review get amber + rose accents. Matches the polish-v2
  // "rare-loud states earn pixels" rule applied across the workspace.
  //
  // Copy uses short labels + agentic attribution: "PIQC confidence: High"
  // vs the repetitive "Confidence: High confidence" that the long-label
  // form produced.
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  const isAlarmConfidence =
    visitConfidence === 'low' || visitConfidence === 'needs_review';
  if (isAlarmConfidence) {
    const confidenceColor: [number, number, number] =
      visitConfidence === 'low'
        ? [180, 83, 9]     // amber-700
        : [190, 18, 60];   // rose-700
    doc.setTextColor(confidenceColor[0], confidenceColor[1], confidenceColor[2]);
  } else {
    doc.setTextColor(60); // quiet gray for high/medium (baseline)
  }
  doc.text(
    `PIQC confidence: ${CONFIDENCE_SHORT_LABELS[visitConfidence]}`,
    margin,
    cursorY,
  );
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60);
  cursorY += 18;

  // Purpose section — placeholder-aware. When the RPC returned the canonical
  // fallback string (parser hasn't extracted a real purpose yet), we frame
  // it explicitly as parser-pending in italic gray so the deliverable
  // doesn't read as "unfinished by the coordinator." When the prose is
  // real, render it as a normal-weight body block.
  doc.setFontSize(8);
  doc.setTextColor(110);
  doc.text('PIQC DRAFTED', margin, cursorY);
  cursorY += 12;
  const isPlaceholderPurpose = packet.snapshot.purpose.trim() === WORKSHEET_PLACEHOLDER_PURPOSE;
  if (isPlaceholderPurpose) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(120);
    const placeholderText =
      'Visit purpose not yet extracted from the protocol. Re-run ingest or fill in the workspace before relying on this draft.';
    const placeholderLines = doc.splitTextToSize(placeholderText, pageWidth - margin * 2);
    doc.text(placeholderLines, margin, cursorY);
    cursorY += placeholderLines.length * 12 + 14;
    doc.setFont('helvetica', 'normal');
  } else {
    doc.setFontSize(10);
    doc.setTextColor(40);
    const purposeLines = doc.splitTextToSize(packet.snapshot.purpose, pageWidth - margin * 2);
    doc.text(purposeLines, margin, cursorY);
    cursorY += purposeLines.length * 12 + 14;
  }

  // Stats line. The "to review" count is colored amber when non-zero so a
  // coordinator scanning the stats line sees open work at a glance.
  // Sprint 6: when filtered, counts scope to the visible item set so the
  // numbers describe what's actually on the page below them.
  const statsItemCount = isFiltered ? filteredItems.length : packet.snapshot.item_count;
  const statsReviewedCount = filteredReviewedCount;
  const statsNeedsReviewCount = filteredNeedsReviewCount;

  doc.setFontSize(9);
  doc.setTextColor(60);
  const baseStatsLine = `${statsItemCount} requirements · ${statsReviewedCount} reviewed · `;
  doc.text(baseStatsLine, margin, cursorY);
  const baseWidth = doc.getTextWidth(baseStatsLine);

  if (statsNeedsReviewCount > 0) {
    // Approximate Tailwind amber-700 (#B45309) — RGB tuned for print
    // contrast on white paper. Exact match isn't required since the PDF
    // viewer's rendering already shifts gamma; this reads clearly amber.
    doc.setTextColor(180, 83, 9);
    doc.setFont('helvetica', 'bold');
  }
  doc.text(`${statsNeedsReviewCount} to review`, margin + baseWidth, cursorY);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60);

  if (packet.snapshot.amendment_version) {
    const widthSoFar = baseWidth + doc.getTextWidth(`${statsNeedsReviewCount} to review`);
    doc.text(` · ${packet.snapshot.amendment_version}`, margin + widthSoFar, cursorY);
  }
  cursorY += 18;

  // Open-items warning banner. When N requirements still need review, the
  // coordinator must not mistake this artifact for a complete deliverable.
  // Sprint 6: scoped to filtered counts so a filtered view doesn't shout
  // about open items the role-view doesn't show.
  if (statsNeedsReviewCount > 0) {
    const bannerHeight = 28;
    const bannerY = cursorY;
    // Amber fill + border, matching the workspace's hard-constraint timing tone.
    doc.setFillColor(254, 243, 199); // amber-100
    doc.setDrawColor(252, 211, 77);  // amber-300
    doc.setLineWidth(0.8);
    doc.rect(margin, bannerY, pageWidth - margin * 2, bannerHeight, 'FD');

    doc.setTextColor(146, 64, 14); // amber-800
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    const bannerLeadingX = margin + 8;
    doc.text('⚠', bannerLeadingX, bannerY + 12);
    doc.setFont('helvetica', 'normal');
    const bannerMessage =
      `${statsNeedsReviewCount} requirement${statsNeedsReviewCount === 1 ? '' : 's'} not yet reviewed. ` +
      'Continue reviewing in PIQC before relying on this draft.';
    const bannerLines = doc.splitTextToSize(
      bannerMessage,
      pageWidth - margin * 2 - 28,
    );
    doc.text(bannerLines, bannerLeadingX + 14, bannerY + 12);
    cursorY += bannerHeight + 14;
    // Reset color state for downstream content.
    doc.setTextColor(60);
    doc.setFont('helvetica', 'normal');
  } else {
    cursorY += 2;
  }

  // ---- Per-phase autotables ----------------------------------------------
  for (const phase of PHASE_ORDER) {
    // Sprint 6: phase grouping operates on the role-filtered view when a
    // role lens is active. Same hide-empty-phases behavior as before; just
    // downstream of the filter.
    const phaseItems = filteredItems.filter((i) => i.phase === phase);
    if (phaseItems.length === 0) continue;

    // Phase title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(20);
    if (cursorY > pageHeight - margin - 80) {
      doc.addPage();
      cursorY = margin + 20;
    }
    doc.text(phaseLabels[phase], margin, cursorY);
    cursorY += 4;

    autoTable(doc, {
      startY: cursorY + 6,
      margin: { left: margin, right: margin },
      head: [['#', 'Requirement', 'Classification', 'Role', 'Timing', 'Status']],
      body: phaseItems.map((row, i) => [
        String(i + 1),
        formatRequirementCell(row),
        CLASSIFICATION_LABEL[row.classification],
        row.role_hint ?? '—',
        formatTiming(row),
        REVIEW_LABEL[row.review_status],
      ]),
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 8.5,
        cellPadding: 4,
        textColor: [30, 30, 30],
        lineColor: [220, 220, 220],
        lineWidth: 0.5,
      },
      headStyles: {
        fillColor: [240, 240, 240],
        textColor: [60, 60, 60],
        fontStyle: 'bold',
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 22 },          // #
        1: { cellWidth: 'auto' },       // Requirement (multi-line)
        2: { cellWidth: 78 },           // Classification
        3: { cellWidth: 60 },           // Role
        4: { cellWidth: 62 },           // Timing
        5: { cellWidth: 60 },           // Status
      },
    });

    // After autotable, cursorY is whatever the table ended at. The
    // augmented `lastAutoTable` is patched onto the doc by jspdf-autotable
    // (see local JsPDFWithAutoTable type above).
    const augmented = doc as JsPDFWithAutoTable;
    const finalY = augmented.lastAutoTable?.finalY ?? cursorY + 100;
    cursorY = finalY + 20;
  }

  // ---- Traceability appendix ---------------------------------------------
  // One row per item with protocol_section + protocol_page. Keeps the audit
  // chain on the worksheet itself so the print artifact is self-contained.
  // Sprint 6: traceability appendix scopes to the filtered view so the
  // appendix doesn't reference rows the body of the worksheet doesn't show.
  const traceableItems = filteredItems.filter(
    (i) => i.traceability.protocol_section || i.traceability.protocol_page !== null,
  );
  if (traceableItems.length > 0) {
    if (cursorY > pageHeight - margin - 80) {
      doc.addPage();
      cursorY = margin + 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(20);
    doc.text('Traceability appendix', margin, cursorY);
    cursorY += 4;

    autoTable(doc, {
      startY: cursorY + 6,
      margin: { left: margin, right: margin },
      head: [['#', 'Requirement', 'Protocol section', 'Page', 'Amendment']],
      body: traceableItems.map((row, i) => [
        String(i + 1),
        row.label,
        row.traceability.protocol_section ?? '—',
        row.traceability.protocol_page !== null ? String(row.traceability.protocol_page) : '—',
        row.traceability.amendment_version ?? '—',
      ]),
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 8,
        cellPadding: 4,
        textColor: [60, 60, 60],
        lineColor: [220, 220, 220],
        lineWidth: 0.5,
      },
      headStyles: {
        fillColor: [240, 240, 240],
        textColor: [60, 60, 60],
        fontStyle: 'bold',
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 130 },
        3: { cellWidth: 40 },
        4: { cellWidth: 80 },
      },
    });
  }

  // ---- DRAFT watermark + header + footer on every page ------------------
  // jsPDF doesn't have a "draw on every page" hook for autotable's added
  // pages; iterate after the body's done. The watermark is the compliance-
  // critical signal — the corner header label is too quiet for a printed
  // artifact that may be photocopied / faxed / scanned mid-stack. A 45°
  // diagonal "DRAFT" across each page is the standard clinical convention.
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // Watermark — 45° diagonal "DRAFT" centered. NOTE: jsPDF has no
    // background-layer primitive, so the watermark is technically a
    // foreground layer drawn LAST. GState opacity makes it read visually
    // as a background (standard jsPDF watermark convention).
    //
    // Watermark visual weight (founder direction post-#141): kept quiet
    // so the coordinator's relationship with their freshly-exported
    // worksheet isn't undermined by an anxiety-inducing alarm. The
    // compliance signal is carried in depth by the corner label, footer
    // disclaimer, server-stamped timestamp, and open-items amber banner —
    // the watermark just needs to be present, not foreground-competing.
    //
    // Three compounding levers tune this:
    //   - Opacity 0.06  (half of Sprint 5's initial 0.12) — barely-there
    //   - Color (180,180,180) — light gray, washes further at low opacity
    //   - 90pt (down from 110pt) — diagonal still legible, less page-eating
    //
    // Result: discernible on purpose if you look for it; ignorable while
    // reading body content. GState reset to 1 after so subsequent
    // header/footer text renders fully opaque.
    const watermarkGState = doc.GState({ opacity: 0.06 });
    doc.setGState(watermarkGState);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(90);
    doc.setTextColor(180, 180, 180);
    doc.text('DRAFT', pageWidth / 2, pageHeight / 2, {
      align: 'center',
      angle: 45,
      baseline: 'middle',
    });
    // Reset opacity so subsequent header/footer text renders fully opaque.
    doc.setGState(doc.GState({ opacity: 1 }));

    // Header band — only show on pages 2+ (page 1 has the title block).
    if (i > 1) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(140);
      doc.text(WORKSHEET_HEADER_LABEL, margin, margin - 12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(140);
      doc.text(packet.snapshot.visit_name, pageWidth - margin, margin - 12, { align: 'right' });
    }

    // Footer band — disclaimer left, generated_at + pagination right.
    // Bumped from 7pt → 8pt: the disclaimer is the most important line
    // on the deliverable; 7pt was at the readability floor.
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(120);
    const disclaimerLines = doc.splitTextToSize(WORKSHEET_DISCLAIMER, pageWidth - margin * 2 - 140);
    doc.text(disclaimerLines, margin, pageHeight - margin + 8);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(formatGeneratedAt(packet.generated_at), pageWidth - margin, pageHeight - margin + 8, {
      align: 'right',
    });
    doc.text(`Page ${i} / ${pageCount}`, pageWidth - margin, pageHeight - margin + 20, {
      align: 'right',
    });
  }

  return doc;
}

// ---------------------------------------------------------------------------
// Layer 3 — download orchestrator
// ---------------------------------------------------------------------------

interface DownloadOptions {
  /** Override for Blob + click (used by tests). */
  triggerDownload?: (filename: string, doc: jsPDF) => void;
}

function defaultDownload(filename: string, doc: jsPDF) {
  // jsPDF.save() handles Blob construction + anchor click + revokeObjectURL
  // for us. Tests can override via opts.triggerDownload.
  doc.save(filename);
}

/**
 * Orchestrates fetch + build + Blob/click for one-visit worksheet export.
 *
 * `roleFilter` defaults to `'all'` (Sprint 5 behavior, no filtering). When
 * non-`'all'`: items are filtered in the build step; filename + PDF header
 * + stats + banner all scope to the role.
 *
 * Returns a Result<{filename, itemCount}> — on success, the filename
 * delivered to the browser; on failure, a human-friendly error message
 * the caller can show in a banner. `itemCount` reflects the FILTERED
 * count when a role filter is active (matches what the PDF actually
 * contains).
 */
export async function downloadVisitWorksheet(
  visitTemplateId: string,
  opts: DownloadOptions = {},
  roleFilter: RoleFilter = 'all',
): Promise<Result<{ filename: string; itemCount: number }>> {
  const fetchResult = await fetchVisitWorksheetPacket(visitTemplateId);
  if (!fetchResult.ok) return fetchResult;

  const packet = fetchResult.data;
  const doc = buildVisitWorksheetPdf(packet, roleFilter);
  const filename = buildWorksheetFilename(packet, roleFilter);

  try {
    (opts.triggerDownload ?? defaultDownload)(filename, doc);
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : 'Failed to trigger download',
    };
  }

  // Counts-only log — no row content goes to the console. `itemCount`
  // here is the count actually delivered to the user (filtered when a
  // role lens is active), not the canonical visit total.
  const deliveredItemCount =
    roleFilter === 'all'
      ? packet.items.length
      : packet.items.filter((i) => itemMatchesRoleFilter(i.role_hint, roleFilter)).length;
  console.info('[vew] worksheet exported', {
    visitTemplateId,
    itemCount: deliveredItemCount,
    roleFilter,
    filename,
  });

  return { ok: true, data: { filename, itemCount: deliveredItemCount } };
}
