// =============================================================================
// Source of Truth Reviewer — Draft Confidence Packet export (PR-6).
//
// Three layers, each separately testable:
//
//   1. fetchDraftConfidencePacket — RPC call, study-scoped, RLS enforced.
//   2. buildDraftConfidencePacketCsv — pure function, JSON → CSV string.
//   3. downloadDraftConfidencePacket — orchestrates fetch + build + Blob/click.
//
// PIQC is a drafting + review aid. The CSV always opens with a clear
// disclaimer. Naming uses "draft confidence" deliberately — never
// "approved" / "signed" / "certified".
// =============================================================================

import { supabase } from '../supabase';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DraftConfidencePacketRow {
  worksheet_item_id:           string;
  worksheet_item_type:         string;
  worksheet_item_text:         string | null;
  confidence_state:            'high' | 'medium' | 'low' | 'needs_review';
  confidence_score:            number | null;
  confidence_reason:           string | null;
  ambiguity_reason:            string | null;
  review_status:               'draft' | 'accepted_for_draft' | 'edited' | 'rejected_from_draft' | 'flagged';
  worksheet_item_version:      number;
  missing_source_reason:       string | null;
  protocol_document_id:        string;
  protocol_document_name:      string | null;
  document_protocol_version:   string | null;
  source_id:                   string | null;
  source_support_type:         'primary' | 'secondary' | 'context' | 'conflict' | null;
  source_protocol_version:     string | null;
  source_page_number:          number | null;
  source_section_number:       string | null;
  source_section_title:        string | null;
  /** Sensitive — never log. */
  quoted_source_text:          string | null;
  has_highlight_coords:        boolean;
  is_item_flagged:             boolean;
  is_source_flagged:           boolean;
  latest_review_action:        string | null;
  latest_review_at:            string | null;
  /** Sensitive — never log. */
  latest_reviewer_note:        string | null;
  /** Sensitive — never log. */
  latest_flag_note:            string | null;
}

export interface DraftConfidencePacket {
  study_id:     string;
  study_code:   string | null;
  generated_at: string;
  rows:         DraftConfidencePacketRow[];
}

// ---------------------------------------------------------------------------
// Disclaimer + column definitions
// ---------------------------------------------------------------------------

export const DRAFT_DISCLAIMER =
  "This export was generated by PIQC as a source-backed draft review aid. "
  + "Final approval, authentication, signature, and controlled release occur "
  + "outside PIQC in the customer's designated process or system.";

/** Column order is the spec order from the prompt — keep stable for downstream. */
export const PACKET_COLUMNS: readonly (keyof DraftConfidencePacketRow)[] = [
  'worksheet_item_id',
  'worksheet_item_type',
  'worksheet_item_text',
  'confidence_state',
  'confidence_score',
  'confidence_reason',
  'ambiguity_reason',
  'review_status',
  'worksheet_item_version',
  'missing_source_reason',
  'latest_review_action',
  'latest_review_at',
  'latest_reviewer_note',
  'is_item_flagged',
  'protocol_document_id',
  'protocol_document_name',
  'document_protocol_version',
  'source_id',
  'source_support_type',
  'source_protocol_version',
  'source_page_number',
  'source_section_number',
  'source_section_title',
  'quoted_source_text',
  'has_highlight_coords',
  'is_source_flagged',
  'latest_flag_note',
] as const;

// ---------------------------------------------------------------------------
// fetchDraftConfidencePacket
// ---------------------------------------------------------------------------

export async function fetchDraftConfidencePacket(
  studyId: string,
): Promise<DraftConfidencePacket> {
  const { data, error } = await supabase.rpc(
    'sotr_get_draft_confidence_packet',
    { p_study_id: studyId },
  );
  if (error) throw error;

  const packet = data as DraftConfidencePacket;
  // Safe log: counts and IDs only — never the rows array (contains quoted
  // protocol text + reviewer notes).
  console.info('[sotr] draft confidence packet fetched', {
    studyId,
    rowCount: packet.rows?.length ?? 0,
  });

  return packet;
}

// ---------------------------------------------------------------------------
// CSV escape helper
// ---------------------------------------------------------------------------

/**
 * Escapes a single value for CSV per RFC 4180:
 *   - null/undefined → empty cell
 *   - boolean → "true" | "false"
 *   - everything else → string, double-quoted, internal quotes doubled
 */
export function csvCell(value: unknown): string {
  if (value === null || value === undefined) return '""';
  if (typeof value === 'boolean') return value ? '"true"' : '"false"';
  const s = String(value).replace(/"/g, '""');
  return `"${s}"`;
}

// ---------------------------------------------------------------------------
// buildDraftConfidencePacketCsv
// ---------------------------------------------------------------------------

/**
 * Pure function: packet → CSV string.
 *
 * Format:
 *   1. "# PIQC Draft Confidence Packet"
 *   2. "# Disclaimer: <DRAFT_DISCLAIMER>"
 *   3. "# Study","<study_code or study_id>"
 *   4. "# Generated","<ISO timestamp>"
 *   5. "# Row count","<n>"
 *   6. (blank line)
 *   7. header row
 *   8. data rows (one per item × source pair; one row with empty source_*
 *      columns when item has zero sources)
 *
 * Rows are emitted in the order returned by the RPC (already deterministic).
 */
export function buildDraftConfidencePacketCsv(
  packet: DraftConfidencePacket,
): string {
  const lines: string[] = [];

  // Metadata block — single-cell quoted lines starting with "#" so spreadsheets
  // and the test suite can both find them deterministically.
  lines.push(csvCell('# PIQC Draft Confidence Packet'));
  lines.push(`${csvCell('# Disclaimer')},${csvCell(DRAFT_DISCLAIMER)}`);
  lines.push(`${csvCell('# Study')},${csvCell(packet.study_code ?? packet.study_id)}`);
  lines.push(`${csvCell('# Generated')},${csvCell(packet.generated_at)}`);
  lines.push(`${csvCell('# Row count')},${csvCell(packet.rows.length)}`);
  lines.push('');

  // Header
  lines.push(PACKET_COLUMNS.map((c) => csvCell(c)).join(','));

  // Data rows
  for (const row of packet.rows) {
    const cells = PACKET_COLUMNS.map((col) => csvCell(row[col]));
    lines.push(cells.join(','));
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// downloadDraftConfidencePacket — browser orchestrator
// ---------------------------------------------------------------------------

interface DownloadOptions {
  /** Override for browser tab open / blob download (used by tests). */
  triggerDownload?: (filename: string, csv: string) => void;
}

function defaultDownload(filename: string, csv: string) {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function todayLocalIsoDate(): string {
  // YYYY-MM-DD in local time; matches ReportsTab's filename convention.
  const d = new Date();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${d.getFullYear()}-${m}-${day}`;
}

export async function downloadDraftConfidencePacket(
  studyId: string,
  studyCodeFallback: string | null,
  opts: DownloadOptions = {},
): Promise<{ rowCount: number; filename: string }> {
  const packet = await fetchDraftConfidencePacket(studyId);
  const csv = buildDraftConfidencePacketCsv(packet);

  const codeForName = (packet.study_code ?? studyCodeFallback ?? 'study')
    .replace(/[^a-zA-Z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'study';
  const filename = `draft-confidence-packet_${codeForName}_${todayLocalIsoDate()}.csv`;

  (opts.triggerDownload ?? defaultDownload)(filename, csv);

  return { rowCount: packet.rows.length, filename };
}
